# https://docs.camunda.io/docs/next/apis-tools/camunda-spring-boot-starter/getting-started/?authentication=oidc#step-3a-configure-the-orchestration-cluster-connection-for-self-managed

camunda.client.mode=self-managed
camunda.client.grpc-address=https://grpc.my.domain.com
camunda.client.rest-address=https://my.domain.com/orchestration

camunda.client.prefer-rest-over-grpc=true

camunda.client.auth.method=oidc
camunda.client.auth.client-id=changeme
camunda.client.auth.client-secret=changeme
# Replace this will depend on your identity provider configuration
camunda.client.auth.issuer-url=https://my.domain.com/auth/realms/camunda-platform
# AUDIENCE will depend on your identity provider configuration
camunda.client.audience=camunda-api
# SCOPE depends on openid and profile
#camunda.client.scope=openid,profile
#camunda.client.tenant-id=<default>

#camunda.client.auth.truststore-path=~/code/camunda-8-helm-recipes/recipes/tls-self-signed-certs/certs/truststore.jks
#camunda.client.auth.truststore-password=camunda

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://my.domain.com/auth/realms/camunda-platform
